name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "* */9 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "1015690517@qq.com"
          git config --local user.name "ww1015690517"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "update per 9h"
          git push
